# Generated by Django 6.0.3 on 2026-03-16 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                ("description", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        limit_choices_to={"role": "journalist"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="newsletters_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for independently published newsletters.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="newsletters",
                        to="news.publisher",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField(blank=True)),
                ("content", models.TextField()),
                ("approved", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "editor"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles_approved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        limit_choices_to={"role": "journalist"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles_authored",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for independently published articles.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="news.publisher",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [("can_approve_article", "Can approve article")],
            },
        ),
        migrations.CreateModel(
            name="APIClientSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=150, unique=True)),
                ("api_key", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "subscribed_journalists",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"role": "journalist"},
                        related_name="api_followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscribed_publishers",
                    models.ManyToManyField(
                        blank=True, related_name="api_subscribers", to="news.publisher"
                    ),
                ),
            ],
            options={
                "ordering": ["client_name"],
            },
        ),
    ]
