# Generated by Django 5.2.13 on 2026-05-21 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsletter",
            name="author",
        ),
        migrations.RemoveField(
            model_name="newsletter",
            name="publisher",
        ),
        migrations.AlterModelOptions(
            name="article",
            options={},
        ),
        migrations.RemoveField(
            model_name="article",
            name="approved_at",
        ),
        migrations.RemoveField(
            model_name="article",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="article",
            name="updated_at",
        ),
        migrations.DeleteModel(
            name="APIClientSubscription",
        ),
        migrations.DeleteModel(
            name="Newsletter",
        ),
    ]
