# Generated by Django 5.2.13 on 2026-05-27 03:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_remove_newsletter_author_remove_newsletter_publisher_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="publisher",
            name="created_at",
        ),
        migrations.CreateModel(
            name="APIClientSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=150, unique=True)),
                ("api_key", models.CharField(max_length=255, unique=True)),
                (
                    "subscribed_journalists",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"role": "journalist"},
                        related_name="api_followers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscribed_publishers",
                    models.ManyToManyField(
                        blank=True, related_name="api_subscribers", to="news.publisher"
                    ),
                ),
            ],
            options={
                "ordering": ["client_name"],
            },
        ),
    ]
